services:
  - type: web
    name: favava-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn server.main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: FLUX_API_KEY
        value: your_black_forest_api_key_here
      - key: FLUX_API_URL
        value: https://api.blackforest.ai/generate
